package com.onurbcd.cli.enums;

import com.onurbcd.cli.util.Constant;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

import static com.onurbcd.cli.util.Constant.*;

@RequiredArgsConstructor
@Getter
public enum FlowField {

    NAME(NAME_ID, NAME_LABEL),
    DESCRIPTION(DESCRIPTION_ID, DESCRIPTION_LABEL),
    PARENT_ID(PARENT_ID_ID, PARENT_ID_LABEL),
    PATH(PATH_ID, PATH_LABEL),
    CATEGORY_ID(CATEGORY_ID_ID, CATEGORY_ID_LABEL),
    INCOME_SOURCE_ID(INCOME_SOURCE_ID_ID, INCOME_SOURCE_ID_LABEL),
    SOURCE_TYPE(SOURCE_TYPE_ID, SOURCE_TYPE_LABEL),
    CURRENCY_TYPE(CURRENCY_TYPE_ID, CURRENCY_TYPE_LABEL),
    BALANCE(BALANCE_ID, BALANCE_LABEL),
    DAY(DAY_ID, DAY_LABEL),
    SOURCE(SOURCE_ID, SOURCE_LABEL),
    CATEGORY(Constant.CATEGORY_ID, CATEGORY_LABEL),
    AMOUNT(AMOUNT_ID, AMOUNT_LABEL),
    CODE(CODE_ID, CODE_LABEL),
    BALANCE_TYPE(BALANCE_TYPE_ID, BALANCE_TYPE_LABEL),
    DOCUMENTS(DOCUMENTS_ID, DOCUMENTS_LABEL),
    DOCUMENTS_IDS(DOCUMENTS_IDS_ID, DOCUMENTS_IDS_LABEL),
    LINK(LINK_ID, LINK_LABEL),
    USERNAME(USERNAME_ID, USERNAME_LABEL),
    PASSWORD(PASSWORD_ID, PASSWORD_LABEL),
    REF_YEAR(REF_YEAR_ID, REF_YEAR_LABEL),
    REF_MONTH(REF_MONTH_ID, REF_MONTH_LABEL),
    BILL_TYPE_ID(BILL_TYPE_ID_ID, BILL_TYPE_ID_LABEL),
    PAID(PAID_ID, PAID_LABEL),
    PAYMENT_TYPE(PAYMENT_TYPE_ID, PAYMENT_TYPE_LABEL);

    private final String id;
    private final String name;
}
